steps:
  
  # Step 2: Unzip the downloaded Packer binary in CentOS VM
  - name: 'centos'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        yum update -y && yum install -y unzip  # Install unzip if not installed
  
options:
  logging: 'CLOUD_LOGGING_ONLY' 