steps:
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cloudbuildpackage/packer.zip', '/workspace/packer.zip']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Unzipping Packer"
        apt-get update && apt-get install -y unzip
        unzip /workspace/packer.zip -d /workspace/packer
        ls -al /workspace/ # List the contents to verify extraction

  # Step 2: Move Packer to /usr/local/bin and ensure it's executable
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Moving Packer to /usr/local/bin"
        mv /workspace/packer/packer /usr/bin/packer
        chmod +x /usr/bin/packer
        ls -al /usr/bin/packer  # List to ensure the binary is moved

  # Step 3: Verify Packer Installation
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'packer --version'  

options:
  logging: 'CLOUD_LOGGING_ONLY' 