
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer-ansible-image',
           '.']

images:
  - 'gcr.io/$PROJECT_ID/packer-ansible:latest'

options:
  logging: 'CLOUD_LOGGING_ONLY' 