
steps:
  - name: 'gcr.io/cloud-builders/wget'
    args: ["https://releases.hashicorp.com/packer/1.9.1/packer_1.9.1_linux_amd64.zip"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:1.9.1',
           '-t', 'gcr.io/$PROJECT_ID/packer',
           '--build-arg', 'PACKER_VERSION=1.9.1',
           '.']
substitutions:
  _PACKER_VERSION: 1.9.1

images:
  - 'gcr.io/$PROJECT_ID/packer:latest'
  - 'gcr.io/$PROJECT_ID/packer:1.9.1'
tags: ['cloud-builders-community']

options:
  logging: 'CLOUD_LOGGING_ONLY' 