steps:
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cloudbuildpackage/packer.zip', '/workspace/packer.zip']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Unzipping Packer"
        apt-get update && apt-get install -y unzip
        unzip /workspace/packer.zip -d /workspace/packer
        ls -al /workspace/ # List the contents to verify extraction

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        /workspace/packer/packer init /workspace/packer-image.pkr.hcl
        /workspace/packer/packer build /workspace/packer-image.pkr.hcl

   

options:
  logging: 'CLOUD_LOGGING_ONLY' 
