steps:
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cloudbuildpackage/packer.zip', '/workspace/packer.zip']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y unzip
        unzip /workspace/packer.zip -d /workspace/packer
        mv /workspace/packer/packer /usr/local/bin/packer
        chmod +x /usr/local/bin/packer
  
options:
  logging: 'CLOUD_LOGGING_ONLY' 