steps:
- name: 'gcr.io/$PROJECT_ID/packer-ansible-image'
  args:
  - init
  - /workspace/packer-build/packer-image.pkr.hcl

- name: 'gcr.io/$PROJECT_ID/packer-ansible-image'
  args:
  - build
  - /workspace/packer-build/packer-image.pkr.hcl



options:
  logging: 'CLOUD_LOGGING_ONLY' 
