steps:
- name: 'gcr.io/$PROJECT_ID/packer-ansible-image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      packer init /workspace/packer-build/packer-image.pkr.hcl

options:
  logging: 'CLOUD_LOGGING_ONLY' 
